#!/bin/sh

config=$1

if test "x$config" = "x" ; then
  config="dev"
fi

CONFIG=conf/mondemand_server_$config.config

rebar3 shell \
  --config $CONFIG \
  --setcookie md_server_ae \
  --name "annotations_elasticsearch_$config" \
  --apps "mondemand_server,mondemand_backend_annotations_elasticsearch"
